server.port=8080
# You could move credentials to environment variables for better security# JDE Orchestrator Config
jde.api.url=http://140.245.21.194/jderest/v3/orchestrator/ORCH_55_CurrencyConvertor
jde.username=THANDE
jde.password=THANDE8
