export const currencyToCountry = {
  USD: 'us',
  EUR: 'eu',
  GBP: 'gb',
  INR: 'in',
  AUD: 'au',
  CAD: 'ca',
  JPY: 'jp',
  CNY: 'cn',
  BRL: 'br',
  ZAR: 'za',
  NZD: 'nz',
  SGD: 'sg',
  HKD: 'hk',
  CHF: 'ch',
  AED: 'ae',
  SAR: 'sa',
  KWD: 'kw',
  QAR: 'qa',
  OMR: 'om',
  BHD: 'bh',
  RUB: 'ru',
  TRY: 'tr',
  KRW: 'kr',
  IDR: 'id',
  THB: 'th',
  MYR: 'my',
  PHP: 'ph',
  VND: 'vn',
  MXN: 'mx',
  ARS: 'ar',
  CLP: 'cl',
  COP: 'co',
  PEN: 'pe',
  ILS: 'il',
  EGP: 'eg',
  PKR: 'pk',
  BDT: 'bd',
  LKR: 'lk',
  NGN: 'ng',
  KES: 'ke',
  GHS: 'gh',
  TWD: 'tw',
  NOK: 'no',
  SEK: 'se',
  DKK: 'dk',
  PLN: 'pl',
  CZK: 'cz',
  HUF: 'hu',
  UAH: 'ua',
  KZT: 'kz'
};

export const getFlagUrl = (currencyCode) => {
  const countryCode = currencyToCountry[currencyCode] || 'un';
  return `https://flagcdn.com/w80/${countryCode.toLowerCase()}.png`;
};
